server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaOrderTopic: "order-topic"
    kafkaOrderStatusTopic: "order-status-topic"
    kafkaMessageService: "order-status-service"
    kafkaMessageGroupId: "kafka-message-group-id"
